### PR TITLE
Added few keywords

### PR DESCRIPTION
**Pull request by ghost**
I added a few basic keywords. I plan to add more but thought I'd get feedback on my initial attempt to improve the software.

### CODE REVIEW

**Comment by muan** [comment]
:+1: but `banner` seems farfetched.

**Comment by ghost** [comment]
"banner" is the number one synonym for "flag" on thesaurus.com

http://thesaurus.com/browse/flag

I also thought I'd mention that I plan on adding more but this was my first commit to the project so I thought I would try out just adding a  few.

**Comment by muan** [comment]
Yea though I won't expect searching the keyword `banner` and the result shows a national flag. 
But English is not my first language, so perhaps @andrew or @jlord won't mind giving me another opinion?

**Comment by ghost** [comment]
Feel free to reject it if you want. The purpose of the commit was for me to get the feel for committing to the project and not the actual content of the commit. —

**Comment by andrew** [comment]
`:banner` makes sense to me, it's on wikipedia: http://en.wikipedia.org/wiki/Banner

**Comment by muan** [comment]
thanks andrew :+1: :heart:

**Pull request merged**
