### PR TITLE
Resolve issues with JSLint

### PR DESCRIPTION
**Pull request by yous**
See http://www.jslint.com.
- Add missing semicolons
- Wrap `if` statement with braces
- Use `!==` and `===` instead of `!=` and `==`
- Use hexadecimal escapes instead of octal escapes
  - Octal escapes have been deprecated in ES5 and they produce syntax errors in strict mode. See https://mathiasbynens.be/notes/javascript-escapes#octal.

### CODE REVIEW

**Comment by muan** [comment]
I don't like semicolons :(

**Comment by yous** [comment]
Okay, then we have to take care of some cases:

``` javascript
a = b + c
(d + e).print()
```

which is equivalent to:

``` javascript
a = b + c(d + e).print();
```

How about other commits? I'll revert the commit which is adding semicolons.

**Comment by muan** [comment]
@yous yea other commits seem fine. Thanks!

**Comment by yous** [comment]
Reverted the commit adding semicolons. :smiley:

**Comment by muan** [comment]
:sparkles:

**Pull request merged**
