### PR TITLE
Add aliasing to the scaled emojis

### PR DESCRIPTION
**Pull request by evilj0e**
These changes will fix a bug with blurred emoji with the scaling property.

### CODE REVIEW

**Comment by muan** [comment]
Hi, I'm not sure what this does, would you provide a screenshot perhaps?

**Comment by evilj0e** [comment]
When the size of the emoji not equal to real size some browsers make them blurred. That change fix that behavior. 
Before: https://yadi.sk/i/Vu_DsJVzhG9B8
After fix: https://yadi.sk/i/k9nZYfPIhG9Cu

**Comment by muan** [comment]
What browsers for example? It seems like this actually make emoji in Chrome on Mac blurry, 

before:

image

after: 

image

Perhaps `translateZ(0)` or the new `will-change` property can achieve what you want here?

**Comment by evilj0e** [comment]
Only `transform(perspective(1px))` make sense here. You're right it's blurry on chrome based browsers. I'm using browser from Yandex. (browser.yandex.ru)

**Comment by muan** [comment]
Well then unfortunately I can't merge this for that it blurs out emoji in Chrome. If you have another fix for this feel free to submit another PR.

**Pull request closed without merging**
