### PR TITLE
Update emojis.json

### PR DESCRIPTION
**Pull request by GoncaloPereiradaSilva**

### CODE REVIEW

**Comment by GoncaloPereiradaSilva** [comment]
I have no idea of what I'm doing..sorry

**Comment by muan** [comment]
No need to apologize! :yum:

Here's an example if you still want to contribute:

```
    ⬇ this is the emoji name
  ━━━━━━━━━━
  "grinning": ["face", "smile", "happy", "joy"],
              ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                   ⬆ these are the keywords
```

You can add more keywords to **an existing emoji**.

So for example:

```
  "grinning": ["face", "smile", "happy", "joy", "ecstatic"],
                                                ━━━━━━━━━━
                                                    ⬆ added this keyword to "grinning"!
```

:heart::heart::heart::heart::heart:

**Comment by GoncaloPereiradaSilva** [comment]
Thank's!!
:smiley::smiley::smiley:

**Pull request closed without merging**
