### PR TITLE
Check for Flash

### PR DESCRIPTION
**Pull request by alfredxing**
:heavy_check_mark: for :zap: using some JavaScript and :see_no_evil: "Copy All" button if :zap: is not detected.
Should :wrench: #52.

JavaScript :zap: testing code from http://stackoverflow.com/a/3336320/1664597.

### CODE REVIEW

**Comment by muan** [comment]
:zap: Seems great. I'd like to have a better fallback when there's no flash though. I'll try to think of something. @joshhunt if you have an idea on what'll be useful for you in those cases, that'd be great.

**Comment by muan** [comment]
@alfredxing thank you so much for the pull request! So sorry for the delay, I just merged this with some minor edits that changes the fallback to the same as iOS products.

**Comment by alfredxing** [comment]
@muan Thanks! No problem :smile:

**Comment by aalfredob2014** [comment]
2015-03-20 9:28 GMT-03:00 Mu-An notifications@github.com:

**Pull request merged**
