### PR TITLE
Add test for line format

### PR DESCRIPTION
**Pull request by yous**
Test that there is no spacing before colon and only one space after colon.

### CODE REVIEW

**Comment by muan** [comment]
Hiiii thanks for taking this on!

I think this test is slightly too complicated though. What about if we just test the line format? like, checking if each line matches this regexp: `/^\s\s"\w+":\s\["\w+"(,\s"\w+")*\],$/gm`, if not then we throw one generic error message about how the line format is wrong, and gives an example.

**Comment by yous** [comment]
Agreed. Then the regular expression will be something like `/^  "[\w-+]+": \["[\w-]+"(, "[\w-]+")*\],$/gm` since `\s` means `[ \t\r\n]` and `\w` means `[A-Za-z0-9_]`.

**Comment by muan** [comment]
:+1: yea yea yea

**Comment by yous** [comment]
Now it checks line format with regular expression. I just write line number to error message, do you have any idea of giving an example?

**Comment by muan** [comment]
@yous let me merge this in first, adding an example shouldn't block this. Thanks a bunch!

**Pull request merged**
