### PR TITLE
Stop updating on window.onhashchange event

### PR DESCRIPTION
**Pull request by jackcarter**
This will make the input more responsive. Before, characters would sometimes get dropped when typing quickly. Also, search() was being called twice per keyup event.

### CODE REVIEW

**Comment by muan** [comment]
Hey! Thanks for this! :)
There's just one problem though:
hasggif

When you change hash in the url, it'll jump back to the original hash. (`happy -> sad -> happy`) I know this is probably not a big issue, but I think one will expect this to work.

**Comment by jackcarter** [comment]
I implemented a workaround -- it's harder than I thought to distinguish automatic hash updates from manual changes.

**Comment by muan** [comment]
Thanks for doing this! Just a heads-up, I'm going to take a bit of time to investigate this. 
This is definitely something I'd like to fix asap, but currently, the complexity of the fix worries me (having not yet looked into it myself).

**Comment by muan** [comment]
Hi @jackcarter, thanks so much for the effort, just got #36 which was simpler and does address the same issue. Really sorry about that, hope you don't mind. 

On the up side, the issue is fixed! :sparkles:

**Pull request closed without merging**
