### PR TITLE
Update emojis.json

### PR DESCRIPTION
**Pull request by schirrel**
As a brazilian i'm adding some portuguese words, i've added at before kissing cat but it you accept i can add more.

### CODE REVIEW

**Comment by muan** [comment]
Hi @jasane, thanks for the contribution, but I'd prefer to leave the main keyword library in English, otherwise it will become gigantic very soon with many different languages. However, I think we can work out a way to make `emoji.muan.co/pt/` which uses `emoji-pt.json` instead of the english library. What do you think? If you are up for it, please change this PR to add a new file instead. :yum: Thanks again.

**Comment by schirrel** [comment]
I appreciate this obviously, but i'm a sort of new on github thing and don't understand what you mean by PR. Thanks for let me help

**Comment by muan** [comment]
No worries at all! :yum: By PR I meant Pull Request, which is this page you are looking at, and we are commenting on. This is a Pull Request. :) 

So what you need to do (obviously only if you're interested in doing) is, go back to https://github.com/muan/emoji, and click on the `+` to add a new file.

image

Calling it `emojis-pt.json` or so, with the same content in [`emojis.json`](https://github.com/muan/emoji/blob/gh-pages/emojis.json), but with portuguese keywords. And purpose the changes again on another branch.

Let me know if any of this is not clear.

**Comment by muan** [comment]
I'll close this for now, but feel free to create another pull! :)

**Pull request closed without merging**
