### PR TITLE
Updated index.html

### PR DESCRIPTION
**Pull request by Deon**
Changed the wording in a sentence.

### CODE REVIEW

**Comment by muan** [comment]
I don't think this change makes it better. If you think so please make a better case by describing the reason why you think the sentence should be changed.

**Comment by Deon** [comment]
I changed it to "project" from "your future self" because of wording and also because adding keywords benefit more people than just the person who is adding the keywords.

**Comment by brianchung808** [comment]
I think the original sentence is fine (and fun)

**Comment by davefp** [comment]
:-1: 
I also like the current version.

**Comment by Deon** [comment]
Original version preferred; closing!

**Pull request closed without merging**
