### PR TITLE
more tags

### PR DESCRIPTION
**Pull request by Roemerb**
All emoji now have at least two keywords :)

### CODE REVIEW

**Comment by hkdobrev** [comment]
@Roemerb You should fix the conflicts by removing the "<<<<" and ">>>" lines and leaving only the correct content. If someone else has added a keyword you should merge them together.

**Comment by Roemerb** [comment]
@hkdobrev latest commit is what you mean right?

**Comment by hkdobrev** [comment]
@Roemerb I see you have removed the lines marking the conflict ranges, but you have left duplicate keys e.g. `restroom`. Let me know if you need any help :sos:

**Comment by Roemerb** [comment]
@hkdobrev Ah I get what you mean ;) I'll change it as soon as I have time :dancer:

**Comment by muan** [comment]
Thanks a bunch both. :yellow_heart:

**Comment by muan** [comment]
Hey thanks @Roemerb, I went ahead, resolved the conflicts and merged the commits. Thanks for contributing!

**Comment by Roemerb** [comment]
You're welcome!

**Pull request merged**
